import type { NextPage } from 'next'
import Head from 'next/head'
import Card from 'components/Card'
import { data } from 'data'
import styles from 'styles/Home.module.scss'

const Home: NextPage = () => {
  const filterTags = ['JavaScript', 'CSS'].sort()

  const filteredData = data.filter((d) => {
    const tags = [d.role, d.level, ...d.languages, ...d.tools]
    const commonTags = tags.filter((tag) => filterTags.includes(tag)).sort()
    return JSON.stringify(commonTags) === JSON.stringify(filterTags)
  })

  console.log(filteredData)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className={styles.header}>
        <h1 className='visually-hidden'>Job Listings</h1>
      </header>
      <main className={styles.main}>
        {data.map((d) => (
          <Card key={d.id} {...d} />
        ))}
      </main>
    </>
  )
}

export default Home
