import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { data } from 'data'
import Card from 'components/Card'
import FilterTagList from 'components/FilterTagList'
import styles from 'styles/Home.module.scss'

const Home: NextPage = () => {
  const [filterTags, setFilterTags] = useState<string[]>([])

  const filteredData = data.filter((d) => {
    const tags = [d.role, d.level, ...d.languages, ...d.tools]
    return filterTags.every((filterTag) => tags.includes(filterTag))
  })

  return (
    <>
      <Head>
        <title>Job Listings</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className={styles.header}>
        <h1 className='visually-hidden'>Job Listings</h1>
      </header>
      <main className={styles.main}>
        <FilterTagList {...{ filterTags, setFilterTags }} />
        {filteredData.map((d) => (
          <Card key={d.id} {...{ d, setFilterTags }} />
        ))}
      </main>
    </>
  )
}

export default Home
